Fix reverse not defined error
Broken by 8f845a5a76

Fixes the below error:
File "/srv/projects/git-reaper/./gitreaper.py", line 97, in _repo_sync
    if reverse:
NameError: name 'reverse' is not defined. Did you mean: 'reversed'?

Signed-off-by: Vijai Kumar K <vijaikumar.kanagarajan@gmail.com>